### ISSUE TITLE
Licensing???

### ISSUE THREAD

**Issue by anne-decusatis** [anne-decusatis/genderamender#12]
What license should we use?

**Comment by fureigh** [comment]
If you're looking for maximum uptake, I'd suggest the MIT License. Personally I like GPL too, but some tech companies (and others) will balk at the requirement that anyone who distributes your code makes it available under the same terms.

Handy quick reference, in case you haven't already seen it: [http://choosealicense.com](http://choosealicense.com)

**Comment by fureigh** [comment]
P.S. Hi, I just heard about this project via Twitter and I'm excited for it to have a license so others can contribute! :)

**Comment by anne-decusatis** [comment]
Hi! Thank you very much for the suggestions and link! Hopefully soon we can get decided on a code of conduct and a license.  (ideally this weekend, if nothing comes up in my life, as happened last week...) I truly believe that this repository is only useful as far as the community is involved in it, and I'm really glad to hear that I'm not the only one excited about it!

**Comment by non** [comment]
+1 on the MIT license from me. I think it's a good place to start.
