### ISSUE TITLE
Add JavaScript rendering to example

### ISSUE THREAD

**Issue by anne-decusatis** [anne-decusatis/genderamender#28]
Because transparency for users is important, and also to prove how easy it is to get gender info from the JSON (you can do it in any language!)

Create some sort of module for this? How does JS packaging work, anyway? Maybe some tests too....

**Comment by nsp** [comment]
Hey, great project! I came here from your PyCon talk, and expected the simple example demo to contain the rendering portion I saw there. Took me a while to realize that it is in the `offline_render_js` branch. I don't know much about JS packaging either, so what do you think about having the demo point to the most feature-full branch? Or just merge and test/package later?

**Comment by anne-decusatis** [comment]
hi @nsp ! The branch `rendering_result_js` contains the demo as well - the offline branch was what I was using for the demos but it's the same code, just without as many calls to the internet (though I suspect I still missed one of them, so it doesn't truly work offline). It's available in this pull request, which I was hoping to find a reviewer for: https://github.com/anne-decusatis/genderamender/pull/31 but I think you're right that the confusion to new people is not worth satisfying my perfectionist tendencies, so I'll go ahead and merge it. Thanks for raising the issue!
