### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by anne-decusatis** [anne-decusatis/genderamender#7]
Right now the genders listed are all in English. If I want to use this at work & elsewhere, we need to be able to support translations. 

-Should we have separate files, e.g. genders_fr.json? If these are being typed in we could also just append to genders.json, but that's not as robust, so I'd prefer country codes in the name. 
-If multiple files, we should probably move genders.json to a subfolder. 
-Does sorted() in alphabetize.py work for i18n?

**Comment by patch** [comment]
> -Does sorted() in alphabetize.py work for i18n?

Yes, but it also needs to be passed a localized comparison key.

Here’s an example using PyICU, which uses the CLDR to provide localized sorting:
https://github.com/patch/unicode-programming/blob/master/sorting/python.md#linguistic-tailoring

**Comment by anne-decusatis** [comment]
renamed this to more accurately reflect changes made in related ticket. closing, will open other issues for different language support
