### ISSUE TITLE
Add more genders

### ISSUE THREAD

**Issue by anne-decusatis** [anne-decusatis/genderamender#9]
Maybe we could start with the list of 50 that Facebook used once upon a time. (I think they don't do it any longer?)

**Comment by patch** [comment]
For reference, here’s the original Facebook list plus the “21 new options for UK users” as reported June 2014:
http://www.telegraph.co.uk/technology/facebook/10930654/Facebooks-71-gender-options-come-to-UK-users.html

**Comment by anne-decusatis** [comment]
added the ones that made sense (read: weren't already available via combination, weren't UK-specific). accidentally committed that change (https://github.com/anne-decusatis/genderamender/commit/ac55c5694fcb2042d8a5b55a972cb1ccf4e30d50)  to master, and just went with it and pushed to master. long day. :/

I'm closing this particular issue, which refers to sourcing from Facebook's list. Of course adding more genders is still a priority, feel free to make a new issue for those.
